Repository OSSPhilippines/philippines-travel-level-map, pull requests merged in 2023-04, with the labels that each got.

#11 📜docs: add license
  license
Labels: chore, docs

#12 📜 chore: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: chore, docs

#13 📜 chore: add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore, docs

#16 📜 chore: update README.md
  README.md
Labels: chore, docs

#20 📦 new: persistent sharing URL
  src/App.css
  src/PhilippinesMapJSX.jsx
  src/components/FacebookLogo.js
  src/pages/Map.js
  src/pages/MapPage.js
  src/utils/constants.js
  src/utils/levelConverter.js
  src/utils/levelConverter.test.js
Labels: feature

#21 🚀 release: v0.1.0
  package-lock.json
  package.json
  public/index.html
  public/social-preview.jpg
Labels: chore, feature, tweak, maintainers only

#38 chore: add deployment based on tag
  .github/workflows/deployment.yml
Labels: chore

#39 chore: add hotfix deployment
  .github/workflows/hotfix.yml
Labels: chore
